multiuser/app1/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from app1 import views


from app1.views import home

app_name= 'app1'

urlpatterns = [
    path('', views.home,name="home"),
    path('adminsignup', views.adminsignup,name="adminsignup"),
    path('studentsignup', views.studentsignup,name="studentsignup"),
    path('teachersignup', views.teachersignup,name="teachersignup"),
    path('login', views.user_login,name="login"),
    path('adminhome', views.adminhome,name="adminhome"),
    path('studenthome', views.studenthome,name="studenthome"),
    path('teacherhome', views.teacherhome,name="teacherhome"),
    path('logout', views.user_logout,name="logout"),


]

multiuser/multiuser/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from app1 import views


from app1.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),

]

multiuser/app1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class CustomUser(AbstractUser):
    place = models.TextField(default="")
    phone = models.IntegerField(default=0)
    is_admin = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


def __str__(self):
    return self.username

multiuser/app1/views.py
from telnetlib import LOGOUT
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import request, HttpResponse
from django.shortcuts import render, redirect

from app1.models import CustomUser


# Create your views here.

def home(request):
    return render(request, "home.html")

def adminsignup(request):
        if (request.method == "POST"):
            u = request.POST['u']
            p = request.POST['p']
            cp = request.POST['cp']
            fn = request.POST['fn']
            ln = request.POST['ln']
            e = request.POST['e']
            ph = request.POST['ph']
            pl = request.POST['pl']

            if (p == cp):
                user = CustomUser.objects.create_user(username=u, password=p, first_name=fn, last_name=ln, email=e,
                                                      phone=ph, place=pl)
                user.is_admin = True
                user.save()
                return home(request)
        return render(request, "adminsignup.html")
def studentsignup(request):
        if (request.method == "POST"):
            u = request.POST['u']
            p = request.POST['p']
            cp = request.POST['cp']
            fn = request.POST['fn']
            ln = request.POST['ln']
            e = request.POST['e']
            ph = request.POST['ph']
            pl = request.POST['pl']

            if (p == cp):
                user = CustomUser.objects.create_user(username=u, password=p, first_name=fn, last_name=ln, email=e,
                                                      phone=ph, place=pl)
                user.is_teacher = True
                user.save()
                return home(request)
        return render(request, "studentsignup.html")


def teachersignup(request):
        if (request.method == "POST"):
            u = request.POST['u']
            p = request.POST['p']
            cp = request.POST['cp']
            fn = request.POST['fn']
            ln = request.POST['ln']
            e = request.POST['e']
            ph = request.POST['ph']
            pl = request.POST['pl']

            if (p == cp):
                user = CustomUser.objects.create_user(username=u, password=p, first_name=fn, last_name=ln, email=e,
                                                      phone=ph, place=pl)
                user.is_teacher = True
                user.save()
                return home(request)
        return render(request, "teachersignup.html")

def user_login(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        user = authenticate(username = u , password = p)

        if user and user.is_admin==True:
            login(request,user)
            return adminhome(request)

        elif user and user.is_student==True:
            login(request,user)
            return studenthome(request)

        elif user and user.is_teacher==True:
            login(request,user)
            return teacherhome(request)

        else:
            return HttpResponse("Invalid")

    return render(request,"login.html")

def adminhome(request):
    return render(request, "adminhome.html")

def studenthome(request):
    return render(request, "studenthome.html")

def teacherhome(request):
    return render(request, "teacherhome.html")


def user_logout(request):
    logout(request)
    return user_login(request)

multiuser/templates/adminhome.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Admin Home</title>
</head>
<body>\<center>
<h1>Welcome to Admin Home</h1>
</center>
</body>
{% endblock %}

multiuser/templates/adminsignup.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <form method="POST">
      {% csrf_token %}
      <h3 class="mt-4">Admin Signup</h3>
      <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="enter the username">
      </div>
      <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="enter password">
      </div>
      <div class="mb-3">
        <label class="form-label">Confirm password</label>
        <input type="password" class="form-control" name="cp" placeholder="re-enter your password">
      </div>
        <div class="mb-3">
        <label class="form-label">First name</label>
        <input type="text" class="form-control" name="fn" placeholder="enter your first name">
      </div>
        <div class="mb-3">
        <label class="form-label">Last name</label>
        <input type="text" class="form-control" name="ln" placeholder="enter your last name">
      </div>
        <div class="mb-3">
        <label class="form-label">Email address</label>
        <input type="email" class="form-control" name="e" placeholder="enter your email address">
      </div>
      <div class="mb-3">
        <label class="form-label">Phone</label>
        <input type="number" class="form-control" name="ph" placeholder="enter your phone number">
      </div>
      <div class="mb-3">
        <label class="form-label">Place</label>
        <input type="text" class="form-control" name="pl" placeholder="enter your place">
      </div>


      <input type="submit" class="form-control">
    </form>
</center>

{% endblock %}

multiuser/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>


<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="#">Multiuser</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:home' %}">Home</a>
        </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Signup
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'app1:adminsignup' %}">Admin</a></li>
            <li><a class="dropdown-item" href="{% url 'app1:teachersignup' %}">Teacher</a></li>
            <li><a class="dropdown-item" href="{% url 'app1:studentsignup' %}">Student</a></li>
          </ul>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:login' %}">Login</a>
        </li>
                <li class="nav-item">
          <a class="nav-link" href="{% url 'app1:logout' %}">Logout</a>
        </li>

      </ul>
      <form class="d-flex" role="search" method="POST" action="">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-danger" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block content %}

{% endblock %}

</body>
</html>

multiuser/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h2 class="mt-4">Welcome to Home page</h2>

{% endblock %}

multiuser/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <form method="POST">
      {% csrf_token %}
      <h3 class="mt-4">Login</h3>
      <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="enter the username">
      </div>
       <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="enter password">
      </div>
        <input type="submit" class="form-control">
    </form>
</center>

{% endblock %}

multiuser/templates/studenthome.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Student Home</title>
</head>
<body>\<center>
<h1>Welcome to Student Home</h1>
</center>
</body>
{% endblock %}

multiuser/templates/studentsignup.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <form method="POST">
      {% csrf_token %}
      <h3 class="mt-4">Student Signup</h3>
      <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="enter the username">
      </div>
      <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="enter password">
      </div>
      <div class="mb-3">
        <label class="form-label">Confirm password</label>
        <input type="password" class="form-control" name="cp" placeholder="re-enter your password">
      </div>
        <div class="mb-3">
        <label class="form-label">First name</label>
        <input type="text" class="form-control" name="fn" placeholder="enter your first name">
      </div>
        <div class="mb-3">
        <label class="form-label">Last name</label>
        <input type="text" class="form-control" name="ln" placeholder="enter your last name">
      </div>
        <div class="mb-3">
        <label class="form-label">Email address</label>
        <input type="email" class="form-control" name="e" placeholder="enter your email address">
      </div>
      <div class="mb-3">
        <label class="form-label">Phone</label>
        <input type="number" class="form-control" name="ph" placeholder="enter your phone number">
      </div>
      <div class="mb-3">
        <label class="form-label">Place</label>
        <input type="text" class="form-control" name="pl" placeholder="enter your place">
      </div>


      <input type="submit" class="form-control">
    </form>
</center>

{% endblock %}

multiuser/templates/teacherhome.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Teacher Home</title>
</head>
<body>\<center>
<h1>Welcome to Teacher Home</h1>
</center>
</body>
{% endblock %}

multiuser/templates/teachersignup.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <form method="POST">
      {% csrf_token %}
      <h3 class="mt-4">Teacher Signup</h3>
      <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="enter the username">
      </div>
      <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="enter password">
      </div>
      <div class="mb-3">
        <label class="form-label">Confirm password</label>
        <input type="password" class="form-control" name="cp" placeholder="re-enter your password">
      </div>
        <div class="mb-3">
        <label class="form-label">First name</label>
        <input type="text" class="form-control" name="fn" placeholder="enter your first name">
      </div>
        <div class="mb-3">
        <label class="form-label">Last name</label>
        <input type="text" class="form-control" name="ln" placeholder="enter your last name">
      </div>
        <div class="mb-3">
        <label class="form-label">Email address</label>
        <input type="email" class="form-control" name="e" placeholder="enter your email address">
      </div>
      <div class="mb-3">
        <label class="form-label">Phone</label>
        <input type="number" class="form-control" name="ph" placeholder="enter your phone number">
      </div>
      <div class="mb-3">
        <label class="form-label">Place</label>
        <input type="text" class="form-control" name="pl" placeholder="enter your place">
      </div>


      <input type="submit" class="form-control">
    </form>
</center>

{% endblock %}